### PR TITLE
allow cache dir to be specified, fix bad free()

### LINKED ISSUE #254: Allow cache directory to be specified
I might have my json event files somewhere other than the the default location in $HOME/.cache, especially if want to ship jevents and the event files bundled together (not downloaded).

Will send a pull request.

### PR DESCRIPTION
**Pull request by travisdowns**
Fixes #254 and #256 .

### CODE REVIEW

File: jevents/jevents.c [hunk 1]
```diff
@@ -58,7 +63,9 @@ static const char *json_default_name(char *type)
 			goto out;
 	}
 
-	cache = getenv("XDG_CACHE_HOME");
+	cache = getenv_copy("JEVENTS_CACHEDIR");
+	if (!cache)
+		cache = getenv_copy("XDG_CACHE_HOME");
```
Comment (travisdowns) [inline jevents/jevents.c:68]: Can't free stuff from `getevn`, but we did below because we don't distinguish between this and the $HOME case (where `cache` does end up with a freeable string).

Easy solution is to `strdup` any string from getenv, so `cache` is always freeable.

File: jevents/jevents.c [hunk 2]
```diff
@@ -58,7 +63,9 @@ static const char *json_default_name(char *type)
 			goto out;
 	}
 
-	cache = getenv("XDG_CACHE_HOME");
+	cache = getenv_copy("JEVENTS_CACHEDIR");
```
Comment (travisdowns) [inline jevents/jevents.c:66]: This is the fix for 254: allow `JEVENTS_CACHEDIR` to be specified which overrides the normal sequence if specified.

**Comment by andikleen** [comment]
Thanks!
